### ISSUE TITLE
Error: Application has not been initialized. Call Initialize() method

### ISSUE THREAD

**Issue by maximelebreton** [wovalle/fireorm#84] opened 2019-10-02 20:23 UTC
Hello there,

When I launch `firebase serve --only functions`, i have this error message:

```node
[1] Error: Application has not been initialized. Call Initialize() method
[1]     at Object.exports.getMetadataStorage (E:\Work\www\lbdc-firebase\back\functions\node_modules\fireorm\lib\src\MetadataStorage.js:56:15)
[1]     at E:\Work\www\lbdc-firebase\back\functions\node_modules\fireorm\lib\src\Decorators\Collection.js:7:27
[1]     at DecorateConstructor (E:\Work\www\lbdc-firebase\back\functions\node_modules\reflect-metadata\Reflect.js:541:33)
[1]     at Object.decorate (E:\Work\www\lbdc-firebase\back\functions\node_modules\reflect-metadata\Reflect.js:130:24)
[1]     at __decorate (E:\Work\www\lbdc-firebase\back\functions\lib\models\band.js:4:92)
[1]     at Object.<anonymous> (E:\Work\www\lbdc-firebase\back\functions\lib\models\band.js:12:8)
```

And I don't understand because Initialize is called.
**index.ts**
```ts
// tslint:disable-next-line: no-import-side-effect
import "reflect-metadata";
import * as fireorm from "fireorm";
import * as admin from "firebase-admin";
import * as functions from "firebase-functions";
import * as onCall from "./onCall"

admin.initializeApp(functions.config().firebase);

const firestore = admin.firestore();
firestore.settings({
  timestampsInSnapshots: true
});
fireorm.Initialize(firestore);

export = {
   ...onCall
}

```
**band.model.ts**
```ts
import { Collection } from "fireorm";

@Collection("Bands")
export default class Band {
  id: string;
  name: string;
}
```

**band.ts**
```ts
import { GetRepository } from "fireorm";
import Band from "./band.model";

const create = async (payload: Band) => {
  const bandRepository = GetRepository(Band);
  let band = new Band();
  band = { ...band, ...payload };
  await bandRepository.create(band);
};
```
**onCall.ts**
```ts
import * as functions from "firebase-functions";
import band from "./band";
import Band from "./band.model";

export const createBand = functions.https.onCall(
  async (payload: Band, context) => {
    await band.create(payload);
  }
);
```

Thanks for your help!

**Comment by maximelebreton** [comment] 2019-10-02 20:49
ok i've removed 
```ts
import "reflect-metadata";
```
and now it's working.


Maybe you should precise on the documentation that we need to:
`npm install typeorm --save` && `npm install reflect-metadata --save`

Isn't it?

Thank you!

**Comment by skalashnyk** [comment] 2019-10-03 04:32
@maximelebreton, where and how do you call your repository class?
It's important, please, add an example.

**Comment by wovalle** [comment] 2019-10-03 07:40
Hey @maximelebreton! I will definitely check this, reflect-metadata shouldn't have anything to do with the Initialize method.

Can you post a tiny reproducible example? 

Thanks!

**Comment by maximelebreton** [comment] 2019-10-03 09:16
@skalashnyk i've updated my initial post with a complete code example, but now it's okay everything works as excepted ;)

@wovalle Yes, I know that `reflect-metadata` isn't related to the `Initialize` method, **but here the story**:
- I `npm install fireorm` and configure it
- On `npm run serve`, I had an error message like "**reflect-metada is missing**"
- But I didn't see any mention of `reflect-metadata` on the the `fireorm` repo
- So i went to the [TypeORM](https://github.com/typeorm/typeorm#installation) repo who mention this:
![image](https://user-images.githubusercontent.com/1072425/66113383-f0f22180-e5cc-11e9-8611-707b2ea1a9fa.png)
- Therefore, I `npm install reflect-metadata` and add `import "reflect-metadata";` to my `index.ts`
- **And then**, I had the `Error: Application has not been initialized. Call Initialize() method`

But now i know this error is caused by the `import "reflect-metadata";` line, that i added by mistake because I thought that `fireorm` was based on `TypeORM`.

Conclusion, maybe you should mention on your documentation that we need to install `reflect-metadata`?

Anyway, thanks for your amazing work! :)

**Comment by wovalle** [comment] 2019-10-03 11:12
Thanks @maximelebreton!

I'll reopen this issue to mention reflect-metadata in the instructions, thanks for noticing!

Regarding the error about `Initialize`, it shouldn't be related to `reflect-metadata`, it should be related to the order you're calling the models/initialize methods. I recognize that this part is not clear and is being worked on #81. After that merge you shouldn't have any problems related to Initialization. I'll ping you when is done.

**Comment by wovalle** [comment] 2019-10-03 11:15
Btw after looking at the files structure the problem is that you're importing `onCall` that is importing `band.model` that is by itself declaring a @Collection before the `Initialize` method is run.

This is something that is confusing to newcomers and will be fixed in the coming days.

**Comment by popcorn245** [comment] 2019-10-05 19:09
Yeah this stumped me last night when I was writing tests. You have to import the models after you initialize the db. 

![image](https://user-images.githubusercontent.com/4184680/66259700-c09bb600-e779-11e9-84c8-eb26ac2a9ca7.png)

**Comment by wovalle** [comment] 2019-10-05 19:24
@popcorn245 yeah thats a temporary workaround until https://github.com/wovalle/fireorm/pull/81 is merged.

**Comment by wovalle** [comment] 2019-10-09 08:20
Update:

Recently added info about reflect-metadata to README (https://github.com/wovalle/fireorm#usage)

**Comment by wovalle** [comment] 2019-10-19 00:36
Hey @popcorn245 and @maximelebreton, now it doesn't matter if you call `Initialize` after importing your models as long as you don't try to access any method of the repositories :)

This issue should be fixed. Let me know if you find something!

**Closed by wovalle** 2019-10-19 00:36 UTC

**Comment by popcorn245** [comment] 2019-10-20 05:06
@wovalle I saw that and I have already refactored my project, thanks for this, great update! ^_^
