### ISSUE TITLE
Search in collection group

### ISSUE THREAD

**Issue by maheshwara-bwd** [wovalle/fireorm#175] opened 2020-08-04 04:54 UTC
I wanted to search through the subcollections of documents and fetch the documents which matches the criteria given.
I went through the firestore documents and found there is a feature known as collection group with which we can achieve this.
So, Is the collection group feature is implemented in fireorm?

If so, can we get any documentation on that.

Thanks in advance.

**Comment by wovalle** [comment] 2020-08-04 10:25
As of today is not implemented in fireorm, but it'll be added! (can't say a timeline though). If you think you can add the support, PRs are welcome!

Closing since is a duplicate of https://github.com/wovalle/fireorm/issues/125

**Closed by wovalle** 2020-08-04 10:25 UTC
